# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15j8VFhdIhjMQBJq9brXo9aAz4p-eXMhX
"""

import numpy as np
from flask import Flask, request, jsonify
from flask import render_template
import pickle
import csv
from flask import send_file

app = Flask(__name__)
#model = pickle.load(open('model.pkl','rb'))

@app.route('/')
def home():
    return render_template('index.html')


@app.route('/predict')
def predict():
    #data = request.get_json(force=True)
    return render_template('predict.html')

@app.route('/result', methods=['POST'])
def result():
    #data = request.get_json(force=True)
    result = request.form
    price=1000
    print (result)
    return render_template('result.html',result=result,price=price)

@app.route('/graph/<city>')
def graph(city):
    return render_template('graph.html',city=city)


@app.route('/downloadCSV') # this is a job for GET, not POST
def download_csv():
    return send_file('Toronto.csv',
                     mimetype='text/csv',
                     attachment_filename='Toronto.csv',
                     as_attachment=True)

'''
@app.route('/api',methods=['POST'])
def predict():
    data = request.get_json(force=True)
    prediction = model.predict([[np.array(data['exp'])]])
    output = prediction[0]
    return jsonify(output)
''' 
if __name__ == '__main__':
  app.run(port=5000, debug=True)